name: API Call

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  api_call:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install axios
      - name: Run API call script
        run: node scripts/api_call.js
      - name: Commit results
        run: |
          git add logs/api_response_*
          git commit -m 'Guardar respuesta de API' || echo "No hay cambios"
          git push
      - name: Send Telegram Notification
        run: node scripts/notify.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
