name: API Call

on:
  schedule:
    - cron: '*/5 * * * *'  # Esto ejecuta la acción cada 5 minutos, ajusta si es necesario.

jobs:
  api_call:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Hacer la llamada a la API de GitHub y guardar la respuesta
      - name: Make API request and save response
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          mkdir -p logs
          curl -s "https://api.github.com/user" -o logs/api_response_$TIMESTAMP.json

      # Paso 3: Extraer el código de estado de la respuesta
      - name: Extract status code
        id: extract_status
        run: |
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" https://api.github.com/user)
          echo "STATUS_CODE=$STATUS_CODE" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      # Paso 4: Configurar la identidad de Git para el bot y hacer commit si hay cambios
      - name: Commit and push API response
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add logs/ || echo "No hay cambios en logs"
          git diff --cached --quiet || (git commit -m "Nueva llamada a la API - $TIMESTAMP" && git push origin master)

      # Paso 5: Enviar notificación de Telegram con el resultado
      - name: Send Telegram notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          MESSAGE="GitHub Action ejecutada: API Call\nFecha y hora: ${{ env.TIMESTAMP }}\nRepositorio: ${{ github.repository }}\nCommit: ${{ github.sha }}\nResultado: ${{ env.STATUS_CODE }}"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="$MESSAGE"
