jobs:
  api_call:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Usa el token de GitHub Actions por defecto

      - name: Run API call script
        run: node scripts/api_call.js

      - name: Commit results
        run: |
          git add logs/api_response_*
          git commit -m 'Guardar respuesta de API' || echo "No hay cambios"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usa el token de GitHub Actions para autenticación

      - name: Send Telegram Notification
        run: node scripts/notify.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
